[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd dashboard && npm ci --include=dev"]

[phases.build]
cmds = ["cd dashboard && npm run build && ls -la dist/"]

[start]
cmd = "cd dashboard && ls -la dist/ && npm run serve"
